### ISSUE TITLE
Fish Spawn On Land??

### ISSUE THREAD

**Issue by emoace** [SteveKunG/FishOfThieves#28]
Hey so I have a weird bug where some of the fish from this mod spawn on land. I am using the most recent 1.19.2 Forge version. I am, however, running a heavily modded instance so I'm not sure if it is just a mod interaction/mixin error that is causing this. I can provide more info if needed later.

**Comment by Zelioth** [comment]
This is also seeing to be an issue for me on my custom pack. 

MC 1.19.2
Forge 43.1.52, and 43.1.53
Fish of Thieves version 2.1.0-rc3

This issue only happens when updating to RC3. When downgrading to version V2.1.0-RC2 the issue is fixed. 

So something in version RC3 changed that causes fish to spawn in insane amount on land and just die from not being in the water.

**Comment by ToxicXremade** [comment]
Same thing with me. Using forge version 43.1.55 and 2.1.0 RC3 for Fish of Thieves version. Hopefully this gets fixed

**Comment by SteveKunG** [comment]
Fixed in both 1.18.2 1.1.0-rc4 and 1.19.2 2.1.0-rc4. I hate Forge.

**Comment by ToxicXremade** [comment]
> Fixed in both 1.18.2 1.1.0-rc4 and 1.19.2 2.1.0-rc4. I hate Forge.

FINALLY
