### ISSUE TITLE
Different enhancements

### ISSUE THREAD

**Issue by Telezhka-the-First** [SteveKunG/FishOfThieves#32]
Here are some enhancements, that I've come up with during translation and generally use of your mod.

- [ ] Add "Салли" as a possible name for completing "lost_sally" advancement, and maybe other languages versions of that name. It would be amazing to point out the exact place, so that all translators can add their language variant, if needed, without asking you to add it manually each time. This way non-English players won't suddenly see a name in English inside of advancement description in their native language.
- [x] Differentiate/explain "Seapost Spacing" and "Seapost Separation". As for right now (there are no seaposts in mod release yet) these parameters seem to change the same thing.
- [ ] Add the ability to block seaposts from spawning. This may be needed for somebody.
- [x] Add translatability to the tooltips — they seem to be hardcoded, which is strange, since parameters themselves are not. This is important because not everybody knows English, and without tooltips it may be hard to understand the meaning of the setting.
- [ ] Separate the setting for the unique NBT data and textures for buckets with fish and fish itself as an item. Since buckets are unstackable anyway, most players would prefer to see the different design, therefore enabling the setting of "Drop and Pick fishes with variant". But this results in cluttering the inventory, since killed fish stacks much worse with this setting.
- [ ] Remove design variant tooltip on the killed fish if "Drop and Pick fishes with variant" setting or its descendant (see previous point) is disabled.
- [ ] Add the ability to completely block some types of fish from spawning. I personally think that all your fish looks amazing, but somebody may have a different opinion. Advancements for catching fish rework may be needed.
- [x] Add the ability to block drop or any other spawn of earthworms, grubs, leeches and anything with the same appearance. I personally just want to look at the beautiful fish, not have hundreds of worms appearing all the time while I'm in cave or anywhere else, min(d)ing my own business.

I guess that upon completion of these requests, your mod will become more user-friendly, flexible and convenient to use.

**Comment by Telezhka-the-First** [comment]
As a possible solution for the last point, you can create a different way of obtaining said critters, requiring specific tool.

**Comment by SteveKunG** [comment]
> Add "Салли" as a possible name for completing "lost_sally" advancement, and maybe other languages versions of that name. It would be amazing to point out the exact place, so that all translators can add their language variant, if needed, without asking you to add it manually each time. This way non-English players won't suddenly see a name in English inside of advancement description in their native language.

I don't think this is a good idea for adding additional languages for Sally. The main reason is the same as "jeb_" or "Dinnerbone" or "Grumm" which doesn't requires translation.

> Differentiate/explain "Seapost Spacing" and "Seapost Separation". As for right now (there are no seaposts in mod release yet) these parameters seem to change the same thing.

Those settings I copied description from https://minecraft.fandom.com/wiki/Custom_world_generation/structure_set.

**spacing**: Average distance between two neighboring generation attempts. Value between 0 and 4096 (inclusive).

**separation**: Minimum distance (in chunks) between two neighboring attempts. Value between 0 and 4096 (inclusive). And be not bigger than `spacing`. The maximum distance of two neighboring generation attempts is `2*spacing - separation`.

Also Seaposts are already in the latest release, but no configs for them yet.

> Add the ability to block seaposts from spawning. This may be needed for somebody.

For now I cannot put a config inside a structure code, because I don't know where to put them to disable seapost generation entirely. If you know mods that can be disable structure generation please send it to me. I'm going to look how they implemented it.

> Separate the setting for the unique NBT data and textures for buckets with fish and fish itself as an item. Since buckets are unstackable anyway, most players would prefer to see the different design, therefore enabling the setting of "Drop and Pick fishes with variant". But this results in cluttering the inventory, since killed fish stacks much worse with this setting.
> Remove design variant tooltip on the killed fish if "Drop and Pick fishes with variant" setting or its descendant (see previous point) is disabled.

This is why those settings are disabled by default. It's just for users who wanted to get a pretty fish items. Not suitable for gameplay because it's cluttering the inventory. I might add an item that act similair like bundle but for fishes only.

> Add the ability to completely block some types of fish from spawning. I personally think that all your fish looks amazing, but somebody may have a different opinion. Advancements for catching fish rework may be needed.

Yes, you can actually do this by using only datapack. Editing `<fish_type>_variant/default_<fish_type>_spawns.json` tag and advancements.

I'd love to see discussions here, I'm glad are you're pay attention with this mod!

**Comment by Telezhka-the-First** [comment]
I understand that this is a tiny inconvenience, and I'm not even sure if it depends on your mod at all, but: is it possible for you to make this "Search" on the top translatable? If yes, in order to speed up the translation, you can append the "ru_ru.json" file by yourself: "Search" is "Поиск" in Russian.
![2023-03-20_07 56 18](https://user-images.githubusercontent.com/90337398/226251386-175deb39-a622-4952-b592-9ef78f9e41b8.png)

**Comment by SteveKunG** [comment]
Unfortunately, this is on ClothConfig side. You have to request them for a translation key.

https://github.com/shedaniel/cloth-config/blob/v10/common/src/main/java/me/shedaniel/clothconfig2/gui/widget/SearchFieldEntry.java#L116
