### ISSUE TITLE
[Fabric 1.20.1] Cant place fish in the frames

### ISSUE THREAD

**Issue by pewblaze** [SteveKunG/FishOfThieves#45]
Hi i cant place any fish in the frames. It doesnt let me do it at all.
Im playing on 1.20.1 Fabric. The mod versions are visible in the log. 
My log from the test world with sodium +  indium:^(I dont think there is anything relevant though)
https://gist.github.com/pewblaze/02b14c5f71e7b820e2d0013f7f8a62a2

My server also says this after trying to add the fish to the frame: (I did a test world without any othe mods to check if its a mod incomp.) But i think its only a info 
`[13:52:50] [Render thread/INFO]: [STDOUT]: TagKey[minecraft:item / croptopia:fishes], TagKey[minecraft:item / minecraft:fishes], TagKey[minecraft:item / c:food], TagKey[minecraft:item / fishofthieves:thieves_fish], TagKey[minecraft:item / forge:food/meat], TagKey[minecraft:item / diet:proteins], TagKey[minecraft:item / fabric:raw_fishes]`

**Comment by SteveKunG** [comment]
Hey, My wiki doesn't tell you clear enough how to get fish inside the plaque. Sorry! I'll update with more informations at some point if I have time. Full time job always got me.
You need a fish bucket instead of raw fish to put them in the fish plaque.

And the log that you shown it is just a tag info. Nothing else.

**Comment by pewblaze** [comment]
oooh i see. wow. i guess cause of the item frames i thought you have to put the dead fish in it ^^" thanks! it works like it should with a bucket :D
